#!/bin/sh
#
# Copyright (c) 2003 Duke University  All rights reserved.
# See COPYING for license statement.
#

prefix=`dirname $0`
prog=`basename $0`

if [ $# -lt 2 ]
then
	echo "usage: $prog <file.model> <file.route>"
	exit 1
fi

model=$1
route=$2

if [ ! -r $model ]
then
	echo "$prog: cannot read $model";
	exit 1
fi

if [ ! -r $route ]
then
	echo "$prog: cannot read $route";
	exit 1
fi

if [ -d $prefix ] 
then $prefix/hostrun $model $prefix/deployhost $*
else hostrun $model deployhost $*
fi
