#!/usr/bin/perl
#
# modelnet  module/modelstat
#
#
# Copyright (c) 2003 Duke University  All rights reserved.
# See COPYING for license statement.
#

use strict;
use IO::File;


my $hopdesc = sysctl("net.inet.ip.modelnet.hopcount")
	or die "modelnet module not installed\n";

my $hopcount = unpack("L",$hopdesc);

my $hopdesc = sysctl("net.inet.ip.modelnet.hopstats");

my @hopstats = unpack("L" x ($hopcount*3),$hopdesc);
print "Hop idx  bytes/pkt  pkts   bytes drops\n";
my $fields=3;
foreach my $i (0..$hopcount-1) {
	my ($pkts,$bytes,$qdrops) = @hopstats[($i*$fields)..($i+1)*$fields-1];
	printf "%6d %6.1f %8d %9d %3d\n",$i,$pkts?$bytes/$pkts:0,
		$pkts,$bytes,$qdrops;
	}

exit 0;

########################


sub sysctl_syscall { syscall(202, @_) }

sub sysctl {
	my ($name,$newbuf) = @_;

	my $mib = pack("LL", 0, 3); # Undocumented
	my $oid = 0 x 56;
	my $oid_len = pack("L", length $oid);
	&sysctl_syscall($mib, ((length $mib)/4), $oid, $oid_len,
		$name, length $name) && die "Sysctl $name mib failed ($!)\n";
	my $buflen = pack("L",1);
	&sysctl_syscall($oid, unpack("L",$oid_len)/4, 0, $buflen, 0, 0)
		&& die "Sysctl $name length probe failed ($!)\n";
	my $oldbuf = 0 x unpack("L",$buflen);
	&sysctl_syscall($oid, unpack("L",$oid_len)/4, $oldbuf, $buflen,
		$newbuf?$newbuf:0, length $newbuf)
		&& die "Sysctl $name failed ($!)\n";
	$oldbuf;
}
